/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

import static sistema.principal.lista;
import static lista_doble.Listadoblecircular.carnet3;
import static lista_doble.Listadoblecircular.name;
import static sistema.principal.pila;
import static sistema.Crearcatedratico.namep;//nombre del catedratico
import static lista_simple.Listasimplecircular.num2;//codigo de curso
import static lista_simple.Listasimplecircular.namec;//nombre del curso
import static lista_simple.Listasimplecircular.cate;//codigo de catedratico 
import static lista_simple.Listasimplecircular.credit;//credito del curso
import static lista_simple.Listasimplecircular.lab;//laboratorio si ciste laboraorio
import asignacion.lista_asignar;
import static asignacion.lista_asignar.ordenasignacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static sistema.asignacion2.model2;
/**
 *
 * @author james
 */
public class asignacion2 extends javax.swing.JFrame {
public static lista_asignar asignacion =new lista_asignar();
  public static DefaultTableModel model2; 
  int orden=0,orden2=2;
/**
     * Creates new form asignacion2
     */
    public asignacion2() {
        initComponents();
         this.setLocationRelativeTo(null);
         model2= (DefaultTableModel)Table2.getModel();
        lista.mostrarlista4();
        lista.ascendente();
        usertext.setText(name);
        carnettext.setText(carnet3);
        boxlab.setVisible(false);
        txtasignarlab.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amenudo = new javax.swing.JComboBox<>();
        seccionclass = new javax.swing.JComboBox<>();
        semestrebox = new javax.swing.JComboBox<>();
        usertext = new javax.swing.JLabel();
        carnettext = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        asignarButon = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        returnbuton = new javax.swing.JButton();
        boxlab = new javax.swing.JComboBox<>();
        txtasignarlab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignacion de Cursos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usac.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pass3.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Usuario:");

        amenudo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Curso" }));
        amenudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amenudoActionPerformed(evt);
            }
        });

        seccionclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Seccion" }));

        semestrebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione el semestre", "Primer Semestre 2019", "Segundo Semestre 2019" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("carnet:");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel5.setText("Seccion:");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel6.setText("Cursos:");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel7.setText("Semestre");

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Curso", "Catedratico", "Seccion", "Creditos", "Desasignar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Table2MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table2);

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel8.setText("Cursos Asignados");

        asignarButon.setText("Asignar");
        asignarButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarButonActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        returnbuton.setText("Regresar");
        returnbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbutonActionPerformed(evt);
            }
        });

        boxlab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecione Si/No", "Si", "No" }));
        boxlab.setToolTipText("");

        txtasignarlab.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        txtasignarlab.setText("Asignar Laboratorio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(amenudo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(seccionclass, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(carnettext, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(returnbuton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(semestrebox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel7)))
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtasignarlab)
                                            .addComponent(boxlab, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(asignarButon)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(carnettext, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(returnbuton, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtasignarlab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amenudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seccionclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semestrebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxlab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(asignarButon)
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amenudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amenudoActionPerformed
  verificarcombo2();
    }//GEN-LAST:event_amenudoActionPerformed

    private void asignarButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarButonActionPerformed
asignar();        // TODO add your handling code here:
    }//GEN-LAST:event_asignarButonActionPerformed

    private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
     recorrertable();    
    }//GEN-LAST:event_Table2MouseClicked

    private void Table2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MousePressed
 
    }//GEN-LAST:event_Table2MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
acceso fr =new acceso();
     fr.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void returnbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbutonActionPerformed
      menu_student fr =new menu_student();
     fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnbutonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       menu_student fr =new menu_student();
     fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing
public void verificarcombo2(){
    boxlab.setVisible(false);
    txtasignarlab.setVisible(false);
    seccionclass.removeAllItems();
     String verificar=amenudo.getSelectedItem().toString();
    lista.buscarseccion(verificar);
    
}

public void recorrertable(){
    int seleccionar;
    try {
        seleccionar=Table2.getSelectedRow();
      boolean sera =(boolean)model2.getValueAt(seleccionar, 5);
        
        System.out.println(seleccionar);
        while(Table2.getRowCount()!=-1&&sera!=true){
                   System.out.println("ai entra");
            
               String carnet=carnettext.getText();
              /* String curso =model2.getValueAt(seleccionar, 1).toString();
                String cate =model2.getValueAt(seleccionar, 2).toString();
                String sec =model2.getValueAt(seleccionar, 3).toString();
                System.out.println(carnet+" , "+curso+" , "+cate+" , "+sec);*/
              
             asignacion.eliminarasignacion(carnet,model2.getValueAt(seleccionar, 1).toString(),
                     model2.getValueAt(seleccionar, 2).toString(),model2.getValueAt(seleccionar, 3).toString());
             

String caldo=carnettext.getText();
limpiaTabla();
asignacion.buscar2(caldo);
orden2=orden2-1;
            System.out.println(orden2);
 orden=orden2;           
        
        }
       } catch (Exception e) {
    }
      
}

public void asignar(){
  /*  String clase=amenudo.getSelectedItem().toString();
    String seccion=seccionclass.getSelectedItem().toString();
    lista.buscarparaasignacion(clase, seccion);
    pila.pilabuscar(cate);
    String status="Reprovado";
    String semestre = semestrebox.getSelectedItem().toString();
    int notafinal=0;*/
    //limpiaTabla();
    try {
        if(orden>2){
      JOptionPane.showMessageDialog(null,"Los sentimos has superado el limite de asgnacion");
  }else if(amenudo.getSelectedIndex()==0){
      JOptionPane.showMessageDialog(null,"seleciona las opciones" );
  }else if(lab.equals("S")){
      
         String clase=amenudo.getSelectedItem().toString();
    String seccion=seccionclass.getSelectedItem().toString();
    lista.buscarparaasignacion(clase, seccion);
    pila.pilabuscar(cate);
    String status="Reprovado";
    String semestre = semestrebox.getSelectedItem().toString();
    int notafinal=0;
    String lab1 = boxlab.getSelectedItem().toString();
 
    if(amenudo.getSelectedIndex()==0||semestrebox.getSelectedIndex()==0||boxlab.getSelectedIndex()==0){
   JOptionPane.showMessageDialog(null,"SeLecione todas la opciones " );
   }else{
        
     asignacion.insertar(num2, namec,namep, cate, seccion, carnet3, name,status, semestre,notafinal,orden,credit,lab1);
asignacion.mostrar(); 
String caldo=carnettext.getText();
limpiaTabla();
asignacion.buscar2(caldo);
orden++;
  }

}else{
    String clase=amenudo.getSelectedItem().toString();
    String seccion=seccionclass.getSelectedItem().toString();
    lista.buscarparaasignacion(clase, seccion);
    pila.pilabuscar(cate);
    String status="Reprovado";
    String semestre = semestrebox.getSelectedItem().toString();
    int notafinal=0; 
      
      if(amenudo.getSelectedIndex()==0||semestrebox.getSelectedIndex()==0){
   JOptionPane.showMessageDialog(null,"SeLecione todas la opciones " );
   }else{
    String lab2="";
    asignacion.insertar(num2, namec,namep, cate, seccion, carnet3, name,status, semestre,notafinal,orden,credit,lab2);
asignacion.mostrar();
String caldo=carnettext.getText();
limpiaTabla();
asignacion.buscar2(caldo);
orden++; 
      }
     
}
//asignacion.buscar(carnet3);
//asignacion.mostrar();
//}
/*else if(ordenasignacion==1){
    ordenasignacion+=1;
    asignacion.insertar(num2, namec,namep, cate, seccion, carnet3, name,status, semestre,notafinal,ordenasignacion,credit);
}  */  

//String codigoCurso, String nombrecurso, String catedratico, String carnetprofe,
         //   String Seccion, String CarnetStudent, String nombrestudent, String status,String semestre, int notafinal, int orden, int credito
asignacion.mostrar(); 
    } catch (Exception e) {
    }
 
}

    
void limpiaTabla(){
while(model2.getRowCount()>0){
    model2.removeRow(0);
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asignacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asignacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asignacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asignacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asignacion2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table2;
    public static javax.swing.JComboBox<String> amenudo;
    private javax.swing.JButton asignarButon;
    public static javax.swing.JComboBox<String> boxlab;
    private javax.swing.JLabel carnettext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnbuton;
    public static javax.swing.JComboBox<String> seccionclass;
    private javax.swing.JComboBox<String> semestrebox;
    public static javax.swing.JLabel txtasignarlab;
    private javax.swing.JLabel usertext;
    // End of variables declaration//GEN-END:variables
}
