/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static sistema.principal.lista;

/**
 *
 * @author james
 */
public class Masivacurso2 extends javax.swing.JFrame {
public static java.io.File fichero;    
public static FileNameExtensionFilter filter;
public static DefaultTableModel model2;
    /**
     * Creates new form Masivacurso2
     */
    public Masivacurso2() {
        initComponents();
        this.setLocationRelativeTo(null);
        model2= (DefaultTableModel)Table1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file25 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        buscarbuton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Carga Masiva");

        buscarbuton.setText("Cargar....");
        buscarbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbutonActionPerformed(evt);
            }
        });

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Curso", "Nombre del Curso", "Codigo de Catedratico", "Creditos", "Laboratorio S/N", "Seccion", "Pre_Requisito", "Post:Requisito"
            }
        ));
        jScrollPane1.setViewportView(Table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscarbuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarbuton)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbutonActionPerformed
       parsearCSV();
    }//GEN-LAST:event_buscarbutonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
 admin_curso df=new admin_curso();
      df.setVisible(true);
      this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
public String abrirCSV() {
        String cadena = "";
         filter = new FileNameExtensionFilter("archivos ipcc", "ipcc");
         file25.setFileFilter(filter);
        int seleccion = file25.showOpenDialog(file25);
          
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
               
               file25.setFileFilter(filter);
            fichero = file25.getSelectedFile();
            cadena = fichero.getAbsolutePath();
        }
        return cadena;
    }
    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }
    public String parsearCSV() {
        FileReader fr = null;
        String cadena = "";
        int contar = 0;
        try {
            File sc = new File(abrirCSV());
            fr = new FileReader(sc);
            
            BufferedReader br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine())!=null) {
                if (contar-1 != 0) {
                    // Biblioteca libro = new Biblioteca();
                    String[] info;
                    info = linea.split(";");
                    if (info[0].equals("") || info[1].equals("") || info[2].equals("") || info[3].equals("")
                            || info[4].equals("") || info[5].equals("")|| info[7].equals("")) {
                        contar++;
                 } else if(isNumeric(info[0])==false||isNumeric(info[2])==false||isNumeric(info[3])==false){
                        contar++;
                    }else{    
                        String numero = info[0];
                        String nombre = info[1];
                        String catedratico = info[2];
                       int creditos =Integer.parseInt(info[3]);
                        String seccion=info[4];
                        String laboratorio = info[5];
                        String prerequisito = info[6];
                        String postrequisito = info[7];
                        

                       /* radomalfanumerico();
                        String password = numero + carga;*/

                       lista.insertar(numero, nombre, catedratico, creditos, laboratorio, prerequisito, postrequisito, seccion);
                    }
                }
                contar++;
            }
        }
        catch(Exception e){
          // e.printStackTrace();
        }finally{
            try{                    
                if( null != fr ){   
                   fr.close();     
                }                  
            }catch (Exception e2){ 
             //  e2.printStackTrace();
            }
        
            lista.mostrarlista3();
        
    }
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masivacurso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masivacurso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masivacurso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masivacurso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masivacurso2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JButton buscarbuton;
    private javax.swing.JFileChooser file25;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
