/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static sistema.Crearcatedratico.carnetp;
import static sistema.Crearcatedratico.namep;
import static sistema.Masivacurso2.fichero;
import static sistema.Masivacurso2.filter;
import static sistema.principal.lista;
import static sistema.asignacion2.asignacion;
import static asignacion.lista_asignar.credit;
import static sistema.principal.add;
import static asignacion.lista_asignar.codigocurso;
/**
 *
 * @author james
 */
public class masivanotas extends javax.swing.JFrame {
public static DefaultTableModel model4; 
    /**
     * Creates new form masivanotas
     */
    public masivanotas() {
        initComponents();
        model4= (DefaultTableModel)Table2.getModel();
        carnettext.setText(carnetp);
        usertext.setText(namep);
        this.setLocationRelativeTo(null);
        lista.buscarcursprofe1(carnetp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file25 = new javax.swing.JFileChooser();
        carnettext = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usertext = new javax.swing.JLabel();
        masivabuton = new javax.swing.JButton();
        semestrebox = new javax.swing.JComboBox<>();
        cursolist1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("carnet:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pass3.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Usuario:");

        masivabuton.setText("Carga Masiva");
        masivabuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masivabutonActionPerformed(evt);
            }
        });

        semestrebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione el semestre", "Primer Semestre 2019", "Segundo Semestre 2019" }));
        semestrebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semestreboxActionPerformed(evt);
            }
        });

        cursolist1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Curso" }));

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "carnet", "Nombre", "Nota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masivabuton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cursolist1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(semestrebox, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carnettext, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(semestrebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(cursolist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(masivabuton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(carnettext, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masivabutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masivabutonActionPerformed
      if(cursolist1.getSelectedIndex()==0||semestrebox.getSelectedIndex()==0){
          JOptionPane.showMessageDialog(null,"Selecione todas las opciones");
      }else{
        parsearCSV();
      }
    }//GEN-LAST:event_masivabutonActionPerformed

    private void semestreboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semestreboxActionPerformed

    }//GEN-LAST:event_semestreboxActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      menu_maestro fg =new menu_maestro();
        fg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing
public String abrirCSV() {
        String cadena = "";
         filter = new FileNameExtensionFilter("archivos ipcnotas", "ipcnotas");
         file25.setFileFilter(filter);
        int seleccion = file25.showOpenDialog(file25);
          
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
               
               file25.setFileFilter(filter);
            fichero = file25.getSelectedFile();
            cadena = fichero.getAbsolutePath();
        }
        return cadena;
    }
    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }
    
    
    public String parsearCSV() {
        FileReader fr = null;
        String cadena = "";
        int contar = 0;
        try {
            File sc = new File(abrirCSV());
            fr = new FileReader(sc);
            
            BufferedReader br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine())!=null) {
                if (contar-1 != 0) {
                    // Biblioteca libro = new Biblioteca();
                    String[] info;
                    info = linea.split(";");
                    if (info[0].equals("") || info[1].equals("")) {
                        contar++;
                   } else if(isNumeric(info[0])==false||isNumeric(info[1])==false){
                        contar++;
                    }else{    
                        String numero = info[0];
                         int nota =Integer.parseInt(info[1]);
                        String curso= cursolist1.getSelectedItem().toString();
                        String semestre=semestrebox.getSelectedItem().toString();
                         if(nota > 60){
              System.out.println(nota);
              String Aprovado="Aprovado";
              asignacion.modificarlista1(numero,carnetp, curso,semestre,codigocurso,Aprovado, nota);
                             System.out.println("guardado correctamente ");
              add.modificarcreditos(numero, credit);
          }else{
              String status="Reprovado";
               asignacion.modificarlista1(numero,carnetp, curso,semestre,codigocurso,status, nota);
              // add.modificarcreditos(carnet, credit);
                             System.out.println("guardado correctamente");
          }
                    }
                }
                contar--;
            }
        }
        catch(Exception e){
          // e.printStackTrace();
        }finally{
            try{                    
                if( null != fr ){   
                   fr.close();     
                }                  
            }catch (Exception e2){ 
             //  e2.printStackTrace();
            }
         limpiaTabla();
   asignacion.listado2(carnetp,semestrebox.getSelectedItem().toString(),cursolist1.getSelectedItem().toString());
            
        
    }
        return null;
    }
      void limpiaTabla(){
while(model4.getRowCount()>0){
    model4.removeRow(0);
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masivanotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masivanotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masivanotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masivanotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masivanotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table2;
    private javax.swing.JLabel carnettext;
    public static javax.swing.JComboBox<String> cursolist1;
    private javax.swing.JFileChooser file25;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton masivabuton;
    private javax.swing.JComboBox<String> semestrebox;
    private javax.swing.JLabel usertext;
    // End of variables declaration//GEN-END:variables
}
